std_msgs/Header header
geometry_msgs/Pose pose
float64 curb_distance
float64 curb_direction
float64 curb_residual
bool option_curb_direction_fix
bool option_curb_horizontal_fix
bool option_curb_traction_fix
bool option_bypass_obstacle
bool option_stop_obstacle
float64 option_speed
uint32 option_cleaning_mode
bool option_traffic_light
bool option_gps_poor_stop
int32 option_turn_signal    # +1: 左转 0: 关闭转向灯 -1: 右转
